apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xo37rttxh-nodejs 
  janus-idp.io/tekton: xo37rttxh-nodejs
  backstage.io/kubernetes-id: xo37rttxh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xo37rttxh-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  